### ISSUE TITLE
add automated checks for proposals

### ISSUE THREAD

**Issue by matthias-heinisch** [ARINC-IA/CSMIM#4]
use github actions for automated quality checks of proposals to this repository. for example:

### GENERAL
- [x] check the syntax/lint is correct yaml

### TYPES
- [x] check the filename follows the pattern csmim.obj.[a-z\.0-9]+.[0-9]+.yaml
- [x] check the file contains an id which matches the filename
- [x] check the file contains the following mandatory attributes, which must not be empty: [id, description, resources]
- [x] check that all resources contain the following mandatory attributes, which must not be empty: [id, mode, type, mandatory, description, parameters]
- [x] check that all resource parameters contain the following mandatory attributes, which must not be empty: [key, type, description]
- [x] check the file does not contain unexpected attributes. expected are all mandatory attributes, plus [supertypes, deprecated, comments]
- [x] check that references supertypes are existing
- [x] check that enum types have enum-values attributes ← maybe harmonize it into values, to be more generic
- [x] check that resource id uses only allowed chars
- [x] check that readable or writable resource is not type void
- [x] check that enum-values are key, name, description
- [x] add racc to resources schema
- [x] check racc for overwritten resources
- ~check that all objects that are not deprecated are linked in the path section~
- ~perform similarity check to prevent redundant objects~

### MANUFACTURERS
- [x] check the filename follows the pattern [A-Z]{3}.yaml
- [x] check the filename contains an id that matches the filename

### PATH
- [x] check that only folders and soft links are placed in the path area
- [x] check that soft links are valid
- [x] check that soft links are referencing files from the types section
- [x] check that the soft links have the same name as the destination filename
- [x] check that the directories in `path/` consist only of allowed chars

**Comment by matthias-heinisch** [comment]
Most checks have been implemented by now. The remaining two will not be implemented for now:
 - no deprecated links in path section: no agreement on this, if allowed or not. Will be discussed when first objects deprecate
 - similarity checks: not needed for now, complex to implement.

**Comment by uwe-salomon** [comment]
More checks from looking at the CSMIM standard:

- [ ] check that resource id uses only allowed chars
- [ ] check that readable or writable resource is not type void
- [ ] check that enum-values are key, name, description
- [ ] check that the directories in `path/` consist only of allowed chars
- [ ] add racc to resources schema
- [ ] check racc for overwritten resources

**Comment by matthias-heinisch** [comment]
thank you - I'll update the description so the status gets updated as we progress

**Comment by uwe-salomon** [comment]
Great! I think we're done.
